#!/bin/bash

### BEGIN INIT INFO
# Provides:          Zisterne-Wasserstand
# Required-Start:    $all
# Required-Stop::    $all
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:
# Default-Stop:      0 1 6
# Short-Description: Start Zisterne-Wasserstand at boot time
# Description:       Manage the Zisterne-Wasserstand daemon, bridge between Midea-Cloud and Loxberry.
### END INIT INFO

#set -e
#set -u
#${DEBIAN_SCRIPT_DEBUG:+ set -v -x}


is_running() {
	/bin/ps -C "zisterne.py" -opid= > /dev/null 2>&1
}

. /lib/lsb/init-functions
case "$1" in
        'start')
                if is_running; then
                    PID=`/bin/ps -C "zisterne.py" -opid=`
                    echo "Zisterne-Wasserstand is already running. PID: $PID"
                else
                    echo "Starting Zisterne-Wasserstand.."
                if [ $EUID -eq 0 ]; then
                    cd REPLACELBPDATADIR
                    su loxberry -c ./zisterne.py > /dev/null 2>&1 &
                    sleep 1
                else
                    cd REPLACELBPDATADIR
                    ./zisterne.py > /dev/null 2>&1 &
                    sleep 1
                fi
                fi;;
        'stop')
                killall zisterne.py
                while is_running
                do
                    wait
                done;;
        'restart')
                $0 stop

                $0 start
                ;;
        '')
                $0 start
                ;;
        'status')
                if is_running; then
                    PID=`/bin/ps -C "zisterne.py" -opid=`
                    echo "Zisterne-Wasserstand is running. PID: $PID"
                else
                    echo "Zisterne-Wasserstand is stopped."
                    exit 1
                fi;;
        *)
                echo "usage $0 start|stop|restart|status" ;;
				
esac

exit 0
